# Generated by Django 2.1.15 on 2020-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPtr',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetimeval', models.DateTimeField(db_column='DateTimeVal')),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=4, max_digits=10, null=True)),
                ('atc_volume', models.DecimalField(blank=True, db_column='ATC_Volume', decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Daily_PTR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundamentalsMFv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetimeval', models.DateTimeField(db_column='DateTimeVal')),
                ('consumption', models.DecimalField(blank=True, db_column='Consumption', decimal_places=4, max_digits=10, null=True)),
                ('wind', models.DecimalField(blank=True, db_column='Wind', decimal_places=4, max_digits=10, null=True)),
                ('pv', models.DecimalField(blank=True, db_column='PV', decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Fundamentals_M_FV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundamentalsMOv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetimeval', models.DateTimeField(db_column='DateTimeVal')),
                ('consumption', models.DecimalField(blank=True, db_column='Consumption', decimal_places=4, max_digits=10, null=True)),
                ('wind', models.DecimalField(blank=True, db_column='Wind', decimal_places=4, max_digits=10, null=True)),
                ('pv', models.DecimalField(blank=True, db_column='PV', decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Fundamentals_M_OV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundamentalsMSv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetimeval', models.DateTimeField(db_column='DateTimeVal')),
                ('consumption', models.DecimalField(blank=True, db_column='Consumption', decimal_places=4, max_digits=10, null=True)),
                ('wind', models.DecimalField(blank=True, db_column='Wind', decimal_places=4, max_digits=10, null=True)),
                ('pv', models.DecimalField(blank=True, db_column='PV', decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Fundamentals_M_SV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundamentalsWAv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetimeval', models.DateTimeField(db_column='DateTimeVal')),
                ('consumption', models.DecimalField(blank=True, db_column='Consumption', decimal_places=4, max_digits=10, null=True)),
                ('wind', models.DecimalField(blank=True, db_column='Wind', decimal_places=4, max_digits=10, null=True)),
                ('pv', models.DecimalField(blank=True, db_column='PV', decimal_places=4, max_digits=10, null=True)),
                ('nuclear', models.DecimalField(blank=True, db_column='Nuclear', decimal_places=4, max_digits=10, null=True)),
                ('coal', models.DecimalField(blank=True, db_column='Coal', decimal_places=4, max_digits=10, null=True)),
                ('lignite', models.DecimalField(blank=True, db_column='Lignite', decimal_places=4, max_digits=10, null=True)),
                ('ccgt', models.DecimalField(blank=True, db_column='CCGT', decimal_places=4, max_digits=10, null=True)),
                ('hydro', models.DecimalField(blank=True, db_column='Hydro', decimal_places=4, max_digits=10, null=True)),
                ('commercial_flow', models.DecimalField(blank=True, db_column='Commercial_flow', decimal_places=4, max_digits=10, null=True)),
                ('ntc', models.DecimalField(blank=True, db_column='NTC', decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Fundamentals_W_AV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundamentalsWFv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetimeval', models.DateTimeField(db_column='DateTimeVal')),
                ('consumption', models.DecimalField(blank=True, db_column='Consumption', decimal_places=4, max_digits=10, null=True)),
                ('wind', models.DecimalField(blank=True, db_column='Wind', decimal_places=4, max_digits=10, null=True)),
                ('pv', models.DecimalField(blank=True, db_column='PV', decimal_places=4, max_digits=10, null=True)),
                ('nuclear', models.DecimalField(blank=True, db_column='Nuclear', decimal_places=4, max_digits=10, null=True)),
                ('net_imports', models.DecimalField(blank=True, db_column='Net_Imports', decimal_places=4, max_digits=10, null=True)),
                ('coal', models.DecimalField(blank=True, db_column='Coal', decimal_places=4, max_digits=10, null=True)),
                ('lignite', models.DecimalField(blank=True, db_column='Lignite', decimal_places=4, max_digits=10, null=True)),
                ('ccgt', models.DecimalField(blank=True, db_column='CCGT', decimal_places=4, max_digits=10, null=True)),
                ('hydro', models.DecimalField(blank=True, db_column='Hydro', decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Fundamentals_W_FV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundamentalsWHv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetimeval', models.DateTimeField(db_column='DateTimeVal')),
                ('consumption', models.DecimalField(blank=True, db_column='Consumption', decimal_places=4, max_digits=10, null=True)),
                ('wind', models.DecimalField(blank=True, db_column='Wind', decimal_places=4, max_digits=10, null=True)),
                ('pv', models.DecimalField(blank=True, db_column='PV', decimal_places=4, max_digits=10, null=True)),
                ('hydro', models.DecimalField(blank=True, db_column='Hydro', decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Fundamentals_W_HV',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpotPrices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetimeval', models.DateTimeField(db_column='DateTimeVal')),
                ('price_forecast', models.DecimalField(blank=True, db_column='Price_Forecast', decimal_places=4, max_digits=10, null=True)),
                ('price_actual', models.DecimalField(blank=True, db_column='Price_Actual', decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Spot_Prices',
                'managed': False,
            },
        ),
    ]
