# Generated by Django 3.0 on 2020-05-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapool', '0002_updatedmc_view1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyptr',
            options={'managed': False, 'ordering': ['-datetimeval', 'country']},
        ),
        migrations.AlterModelOptions(
            name='fundamentalsmfv',
            options={'managed': False, 'ordering': ['-datetimeval', 'country']},
        ),
        migrations.AlterModelOptions(
            name='fundamentalsmov',
            options={'managed': False, 'ordering': ['-datetimeval', 'country']},
        ),
        migrations.AlterModelOptions(
            name='fundamentalsmsv',
            options={'managed': False, 'ordering': ['-datetimeval', 'country']},
        ),
        migrations.AlterModelOptions(
            name='fundamentalswav',
            options={'managed': False, 'ordering': ['-datetimeval', 'country']},
        ),
        migrations.AlterModelOptions(
            name='fundamentalswfv',
            options={'managed': False, 'ordering': ['-datetimeval', 'country']},
        ),
        migrations.AlterModelOptions(
            name='fundamentalswhv',
            options={'managed': False, 'ordering': ['-datetimeval', 'country']},
        ),
        migrations.AlterModelOptions(
            name='spotprices',
            options={'managed': False, 'ordering': ['-datetimeval', 'country']},
        ),
    ]
