# Generated by Django 2.1.15 on 2020-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoDetNew',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ftppath', models.CharField(db_column='FtpPath', max_length=255)),
                ('filename', models.CharField(db_column='FileName', max_length=120)),
                ('active', models.BooleanField(db_column='Active')),
                ('tableto', models.CharField(db_column='TableTo', max_length=50)),
                ('fieldto', models.CharField(blank=True, db_column='FieldTo', max_length=50, null=True)),
                ('insertminutes', models.IntegerField(blank=True, db_column='InsertMinutes', null=True)),
                ('daybefore', models.BooleanField(db_column='DayBefore')),
                ('dayafter', models.BooleanField(db_column='DayAfter')),
                ('fieldname', models.CharField(blank=True, db_column='FieldName', max_length=25, null=True)),
                ('timefrom', models.TimeField(blank=True, db_column='TimeFrom', null=True)),
                ('timeto', models.TimeField(blank=True, db_column='TimeTo', null=True)),
                ('timeselection', models.TimeField(blank=True, db_column='TimeSelection', null=True)),
                ('headerrow', models.IntegerField(blank=True, db_column='HeaderRow', null=True)),
                ('usetimeframe', models.BooleanField(blank=True, db_column='UseTimeFrame', null=True)),
            ],
            options={
                'db_table': 'Meteo_Det_New',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeecaoDet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entsoe_curves', models.CharField(max_length=100)),
                ('fieldname', models.CharField(blank=True, db_column='FieldName', max_length=20, null=True)),
                ('active', models.BooleanField(db_column='Active')),
            ],
            options={
                'db_table': 'Seecao_Det',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpotDetNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curvesnameprice', models.CharField(db_column='CurvesNamePrice', max_length=150)),
                ('active', models.BooleanField(db_column='Active')),
                ('tableto', models.CharField(db_column='TableTo', max_length=50)),
                ('insertminutes', models.IntegerField(blank=True, db_column='InsertMinutes', null=True)),
                ('daybefore', models.BooleanField(db_column='DayBefore')),
                ('dayafter', models.BooleanField(blank=True, db_column='DayAfter', null=True)),
            ],
            options={
                'db_table': 'Spot_Det_New',
                'managed': False,
            },
        ),
    ]
