# Generated by Django 2.1.15 on 2020-04-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('abbr', models.CharField(db_column='Abbr', max_length=10)),
                ('abbr_nrg', models.CharField(db_column='Abbr-nrg', max_length=10)),
                ('regionof', models.IntegerField(db_column='RegionOf')),
                ('abbr_wattsight', models.CharField(blank=True, db_column='Abbr_WattSight', max_length=10, null=True)),
                ('abbr_entsoe', models.CharField(blank=True, db_column='Abbr_Entsoe', max_length=2, null=True)),
                ('countryft', models.NullBooleanField(db_column='CountryFT')),
            ],
            options={
                'db_table': 'Country',
                'managed': False,
            },
        ),
    ]
