# Generated by Django 3.0 on 2020-04-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': False, 'ordering': ('countryft', 'name')},
        ),
    ]
