# Generated by Django 2.1.15 on 2020-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timefrom', models.TimeField(db_column='TimeFrom')),
                ('timeto', models.TimeField(db_column='TimeTo')),
                ('description', models.CharField(db_column='Description', max_length=250)),
                ('active', models.BooleanField(db_column='Active')),
            ],
            options={
                'db_table': 'Scheduled_Task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('description', models.CharField(db_column='Description', max_length=250)),
            ],
            options={
                'db_table': 'Scheduler',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('url', models.CharField(db_column='Url', max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('active', models.BooleanField(db_column='Active')),
            ],
            options={
                'db_table': 'Task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskParam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(db_column='Param_Name', max_length=100)),
                ('param_value', models.CharField(db_column='Param_Value', max_length=100)),
            ],
            options={
                'db_table': 'Task_Param',
                'managed': False,
            },
        ),
    ]
