# Generated by Django 3.0 on 2020-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(db_column='DateTime')),
                ('description', models.CharField(db_column='Description', max_length=250)),
                ('log', models.TextField(db_column='Log')),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'Schedule_Log',
                'ordering': ['-datetime'],
                'managed': False,
            },
        ),
    ]
